#!/bin/bash

LANG=C

# Include shared functions.
. /var/lib/simple_baremetal/scripts/include

# Update snapshot variables.
update_ss_vars

# A reboot to the working BASELINE snapshot should be done only if:
#   - a working BASELINE snapshot exists
#   - the working BASELINE is the default
#   - the working BASELINE is not the active one
[ -z "${ss_baseline_working}" ] && exit_on_error "No working BASELINE snapshot found! Exiting."   
[ "${ss_baseline_working}" != "${ss_default}" ] && exit_on_error "The working BASELINE snapshot is not the default! Exiting."
[ "${ss_baseline_working}" == "${ss_active}" ] && exit_on_error "The working BASELINE snapshot is already the active one! Exiting."

# Reboot.
log "Doing reboot..."
reboot

