#!/bin/bash

LANG=C

# Include shared functions.
. /var/lib/simple_baremetal/scripts/include

# Update snapshot variables.
update_ss_vars

# We rollback to the recovery snapshot only if:
#   - a recovery snapshot exists
#   - the recovery snapshot is not the active snapshot
[ -z "${ss_recovery}" ] && exit_on_error "No recovery snapshot found! Exiting."   
[ "${ss_recovery}" == "${ss_active}" ] && exit_on_success "The recovery snapshot is already the active one! Exiting."

# Set recovery snapshot as default.
subvol=$(btrfs subvolume list -t / | expand | grep " @/.snapshots/${ss_recovery}/snapshot$" | tr -s ' ' | cut -d ' ' -f1)
[ -z "${subvol}" ] && exit_on_error "Something went wrong. No subvolume found for snapshot ${ss_recovery}."
btrfs subvolume set-default ${subvol} /
log "Recovery snapshot (${ss_recovery}) set as default (subvol=${subvol})."

# Bye.
exit 0
