#!/bin/bash
set -e

baseline='BASELINE'    # Existing snapshot to rollback to.
recovery='RECOVERY'    # Name for snappshot to go to back later.

# Get baseline snapshot.
id=$(grub2-once --list | grep ",${baseline})$" | tr -s ' ' | cut -d ' ' -f 2)
if [ -z "${id}" ] ; then
    echo "Could not find boot entry for snapshot \"${baseline}\"!" 2>&1
    exit 1
fi

# Create recovery snapshot.
recovery="${recovery} $(date +'%d-%m-%Y %H:%M:%S')"
echo "Create recovery snapshot \"${recovery}\"."
snapper --config root create -d "${recovery}"

# Boot into baseline snapshot
grub2-once ${id}
reboot
