#!/bin/bash

set -e
LANG=C

# Include shared functions.
. "${0%*${0##*/}}include"

# Reboot if necessary.
set_status  boot2baseline_initiate
active=$(snapper --csvout  -c root list --disable-used-space --columns number,active | grep ',yes$' | cut -d ',' -f1)
working_snapshot=$(< "${working_snapshot_file}")
if [ ${active} -eq ${working_snapshot} ] ; then
    log 'Reboot not required'
    set_status  boot2baseline_not_needed
    exit 0
fid
reboot
