#!/bin/bash
set -e

# Check for baseline snapshot.
if ! grub2-once --list | grep -q ',BASELINE)$' ; then
    msg='No BASELINE boot entry found!'
    logger -t simple_baremetal "${msg}"
    echo "${msg}"
    exit 1
fi
#sync
#snapper --config root create -d RECOVERY
msg='RECOVERY snapshot created.'
logger -t simple_baremetal "${msg}"
echo "${msg}"

# Boot into baseline snapshot
grub2-once BASELINE
msg='BASELINE snapshot created. Rebooting...'
logger -t simple_baremetal "${msg}"
echo "${msg}"
#systemctl reboot

