#!/bin/bash

set -e
LANG=C

# Include shared functions.
. "${0%*${0##*/}}include"

# Check and set status.
set_status  rollback2recovery

exit 0

# Check if we are already in the recovery snapshot.
active=$(snapper --csvout  -c root list --disable-used-space --columns number,active | grep ',yes$' | cut -d ',' -f1)
recovery_snapshot=$(< "${recovery_snapshot_file}")
if [ ${active} -eq ${recovery_snapshot} ] ; then
    log 'Recovery snapshot already active. No rollback required'
    exit 0
fi

# Rollback to recovery point only, if we are not already there.
log "Recovery rollback to snapshot #${target}."
output=$(snapper -c root rollback -d 'simple_baremetal recovery' ${target})
log "${output}"
new_recovery_snapshot=$(grep 'Setting default subvolume to snapshot' <<< "${output}" | sed 's/[^0-9]//g') 
log "Recovery snapshot: ${recovery_snapshot} -> ${new_recovery_snapshot}"
echo "${new_recovery_snapshot}" > "${recovery_snapshot_file}"
